import { toTaxonomySlug } from "@utils/slugs";

// Whole-slug overrides for labels the word rules can't produce (punctuation, versions).
const SLUG_LABELS: Record<string, string> = {
  "self-hosting": "Self-Hosting",
  "self-hosted": "Self-Hosted",
  "web-development": "Web Development",
  "next-js": "Next.js",
  "bunny-net": "Bunny.net",
  "lets-encrypt": "Let's Encrypt",
  "gpt-5": "GPT-5",
  "2-5gbe": "2.5GbE",
  "10gbe": "10GbE",
  cicd: "CI/CD",
};

const WORD_LABELS: Record<string, string> = {
  "2fa": "2FA",
  adk: "ADK",
  ai: "AI",
  api: "API",
  asus: "ASUS",
  aws: "AWS",
  caldigit: "CalDigit",
  cdn: "CDN",
  cli: "CLI",
  cloudpanel: "CloudPanel",
  cms: "CMS",
  cpanel: "cPanel",
  crowdsec: "CrowdSec",
  css: "CSS",
  devops: "DevOps",
  dns: "DNS",
  easypanel: "EasyPanel",
  elevenlabs: "ElevenLabs",
  fasthtml: "FastHTML",
  filebrowser: "FileBrowser",
  github: "GitHub",
  glm: "GLM",
  gpt: "GPT",
  gpu: "GPU",
  https: "HTTPS",
  i18n: "i18n",
  ia: "IA",
  ide: "IDE",
  javascript: "JavaScript",
  k2: "K2",
  lancedb: "LanceDB",
  llm: "LLM",
  lvm: "LVM",
  macbook: "MacBook",
  macos: "macOS",
  mcp: "MCP",
  minimax: "MiniMax",
  moviepy: "MoviePy",
  n8n: "n8n",
  nas: "NAS",
  nextdns: "NextDNS",
  nfs: "NFS",
  nicegui: "NiceGUI",
  nocodb: "NocoDB",
  npm: "npm",
  nvme: "NVMe",
  oauth: "OAuth",
  oci: "OCI",
  oled: "OLED",
  openclaw: "OpenClaw",
  opencode: "OpenCode",
  openrouter: "OpenRouter",
  paas: "PaaS",
  pdf: "PDF",
  pgvector: "pgvector",
  php: "PHP",
  pinchtab: "PinchTab",
  pip: "pip",
  pm2: "PM2",
  postgresql: "PostgreSQL",
  rag: "RAG",
  rustfs: "RustFS",
  s3: "S3",
  scp: "SCP",
  searxng: "SearXNG",
  seo: "SEO",
  smtp: "SMTP",
  sqlite: "SQLite",
  ssg: "SSG",
  ssh: "SSH",
  svg: "SVG",
  tanstack: "TanStack",
  tinyfish: "TinyFish",
  tmux: "tmux",
  tts: "TTS",
  typescript: "TypeScript",
  ufw: "UFW",
  ui: "UI",
  ups: "UPS",
  url: "URL",
  uv: "uv",
  venv: "venv",
  vpn: "VPN",
  vps: "VPS",
  webdav: "WebDAV",
  wezterm: "WezTerm",
  woocommerce: "WooCommerce",
  wordpress: "WordPress",
  youtube: "YouTube",
};

/** Display label for a tag or category slug ("ai-agents" → "AI Agents"). URLs keep using the slug. */
export function formatTaxonomyLabel(value: string): string {
  const slug = toTaxonomySlug(value);
  if (!slug) return value;
  if (SLUG_LABELS[slug]) return SLUG_LABELS[slug];

  return slug
    .split("-")
    .map((word) => WORD_LABELS[word] ?? word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
